

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: team3
  labels:
    app: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx 
    spec:
      containers:
     - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 80
        
         
        
      
          

      



apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: team3
  labels:
    app: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx 
    spec:
      containers:
     - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 80
        
         
        
      
          

      




apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: team3
  labels:
    app: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx 
    spec:
      containers:
     - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 80
        
         
        
      
          

      




apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: team3
  labels:
    app: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx 
    spec:
      containers:
     - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 80
        
         
        
      
          

      




apiVersion: apps/v1
kind: service
metadata:
  name: nginx-deployment
  namespace: team3
  labels:
    app: nginx-app
spec:
  service type: load balancer
  selector:
    matchLabels:
      app: nginx 
    spec:
      containers:
     - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 80
        
         
        
      
          

      

