apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-pod
  namespace: team1
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoint
  - pods
   verbs: ["get", "list", "watch","delete"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 
subjects:
- kind: ServiceAccount
  name: default
  namespace: team1
